### ISSUE TITLE
How do you launch this application?

### ISSUE THREAD

**Issue by happyrwandan** [h0tw4t3r/parrot-software-center#9]
Greetings, 

I cloned this project in my /opt/ directory, ran the : yarn install command, all good but now where's the binary or executable file for this application?

**Comment by dalechyn** [comment]
Greetings! Binary releases are available in this repository in the Releases section: https://github.com/h0tw4t3r/parrot-software-center/releases

However, this tool should not be considered as "fully" working. It's still in alpha stage.

You should be able to run it, by running `yarn start`, after `yarn install`, but it will launch in development mode

**Comment by happyrwandan** [comment]
Thank you sir! appreciate your time and efforts!
